# Generated by Django 6.0 on 2026-03-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendships',
            options={'verbose_name_plural': 'Friendships'},
        ),
    ]
