# Generated by Django 6.0.3 on 2026-03-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tdlist',
            options={'verbose_name_plural': 'TDLists'},
        ),
    ]
